06-Large-Flask-apps/01-Using-blueprints/myproject/models.py
# models.py
# setup db object inside __init__.py initialization
# of the project
from myproject import db

###############
# DB Models ###
###############


class Puppy(db.Model):
    __tablename__ = 'puppies'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Text)
    # one to one, a puppy can have one owner
    owner = db.relationship('Owner', backref='puppy', uselist=False)

    def __init__(self, name):
        self.name = name

    def __repr__(self):
        if self.owner:
            return f"Puppy name is {self.name} and owner is {self.owner.name}."
        else:
            return f"Puppy name is {self.name} and is ready for adoption!"


class Owner(db.Model):
    __tablename__ = 'owners'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Text)

    puppy_id = db.Column(db.Integer, db.ForeignKey('puppies.id'))

    def __init__(self, name, puppy_id):
        self.name = name
        self.puppy_id = puppy_id

    def __repr__(self):
        return f"{self.name}"

06-Large-Flask-apps/01-Using-blueprints/myproject/owners/forms.py
# Owners --> forms.py

from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField


class AddForm(FlaskForm):
    name = StringField('Name of owner: ')
    puppy_id = IntegerField('ID of the puppy to adopt : ')
    submit = SubmitField('Add Owner')

06-Large-Flask-apps/01-Using-blueprints/myproject/puppies/forms.py
# Puppies --> forms.py

from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField


class AddForm(FlaskForm):

    name = StringField('Name of Puppy: ')
    submit = SubmitField('Add Puppy')


class DelForm(FlaskForm):

    id = IntegerField('Id Number of Puppy to remove: ')
    submit = SubmitField('Remove Puppy')

06-Large-Flask-apps/01-Using-blueprints/myproject/__init__.py
# __init__.py initialization of the project

from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate


app = Flask(__name__)

app.config['SECRET_KEY'] = 'SECRETKEY'

# SQL database section
app.config['SQLALCHEMY_DATABASE_URI'] = 'postgresql+psycopg2://flask:flask@db:5432/puppies_dev'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)
Migrate(app, db)

# Needs to be after the db registration
# else raise an error
from myproject.puppies.views import puppies_bp
from myproject.owners.views import owners_bp


app.register_blueprint(owners_bp, url_prefix='/owners')
app.register_blueprint(puppies_bp, url_prefix='/puppies')

06-Large-Flask-apps/01-Using-blueprints/myproject/owners/views.py
# owners --> views

from flask import Blueprint, render_template, redirect, url_for
from myproject import db
from myproject.models import Owner
from myproject.owners.forms import AddForm

owners_bp = Blueprint('owners', __name__, template_folder='templates/owners')


# add owner for adopted puppy
@owners_bp.route('/add', methods=['GET', 'POST'])
def add_owner():

    form = AddForm()

    # add new puppy to the db
    if form.validate_on_submit():

        name = form.name.data
        puppy_id = form.puppy_id.data

        new_owner = Owner(name, puppy_id)
        db.session.add(new_owner)
        db.session.commit()

        # puppies.list references the template
        return redirect(url_for('puppies.list_pup'))

    return render_template('add_owner.html', form=form)

06-Large-Flask-apps/01-Using-blueprints/myproject/puppies/views.py
# puppies --> views
from flask import Blueprint, render_template, redirect, url_for
from myproject import db
from myproject.models import Puppy
from myproject.puppies.forms import AddForm, DelForm


# Blueprints
puppies_bp = Blueprint('puppies', __name__, template_folder='templates/puppies')

# add new puppy
@puppies_bp.route('/add', methods=['GET', 'POST'])
def add_pup():

    form = AddForm()

    # add new puppy to the db
    if form.validate_on_submit():
        name = form.name.data

        new_pup = Puppy(name)
        db.session.add(new_pup)
        db.session.commit()

        return redirect(url_for('puppies.list_pup'))

    return render_template('add.html', form=form)


# list of puppies
@puppies_bp.route('/list')
def list_pup():

    puppies = Puppy.query.all()
    return render_template('list.html', puppies=puppies)


# a puppy was adopted and taken home
@puppies_bp.route('/delete', methods=['GET', 'POST'])
def del_pup():

    form = DelForm()

    if form.validate_on_submit():
        id = form.id.data

        pup = Puppy.query.get(id)
        db.session.delete(pup)
        db.session.commit()

        return redirect(url_for('puppies.list_pup'))
    return render_template('delete.html', form=form)

06-Large-Flask-apps/01-Using-blueprints/myproject/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
    <title>Puppy Adoption Site</title>
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class='navbar-nav'>
            <a class='nav-item nav-link' href='{{ url_for("index") }}'>Home</a>
            <a class='nav-item nav-link' href='{{ url_for("puppies.add_pup") }}'>Add Pup</a>
            <a class='nav-item nav-link' href='{{ url_for("owners.add_owner") }}'>Register Owner</a>
            <a class='nav-item nav-link' href='{{ url_for("puppies.list_pup") }}'>List of Pups</a>
            <a class='nav-item nav-link' href='{{ url_for("puppies.del_pup") }}'>Delete Pup</a>
        </div>
    </nav>

    {% block content %}

    {% endblock %}

</body>

</html>

06-Large-Flask-apps/01-Using-blueprints/myproject/templates/home.html
{% extends 'base.html' %}

{% block content %}

<div class='jumbotron'>
    <h1>Welcome!</h1>
</div>

{% endblock %}